### ISSUE TITLE
Create dbt converter for Airbyte Tiktok Marketing source connector

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte-dbt-models#31]
The goal of this task is to ensure the Airbyte Tiktok Marketing connector output can be used to run [Fivetran's dbt analytical model](https://hub.getdbt.com/fivetran/tiktok/latest/).

**Definition of Done:** 
* Create a pull request that adds new tables or views, enabling the execution of Fiventran's dbt with Airbyte output data.
* Update the documentation inside the connector folder to explain how to configure the user dbt package to run the analytical model.

**Resources:** 
* Check example of how it was done for [Zendesk Support](link) connector 
```[tasklist]
### Tasks
- [x] tiktok_ads__ad_group_history
- [x] tiktok_ads__ad_group_report_hourly
- [x] tiktok_ads__ad_history
- [x] tiktok_ads__ad_report_hourly
- [x] tiktok_ads__advertiser
- [x] tiktok_ads__campaign_history
- [x] tiktok_ads__campaign_report_hourly
```

**Comment by topefolorunso** [comment]
I'd like to claim this next @marcosmarxm. Waiting to merge https://github.com/airbytehq/airbyte/pull/43400 to test and proceed with #8

**Comment by fvgm-spec** [comment]
Hey @marcosmarxm
Could you please assign it to me?

**Comment by fvgm-spec** [comment]
Hey @marcosmarxm what would be the dbt model to analyze on the first step of this issue, as only 2 Tiktok related models in dbt Fivetran repo are:

* [tiktok_ads](https://hub.getdbt.com/fivetran/tiktok_ads/latest/)
* [tiktok_ads_source](https://hub.getdbt.com/fivetran/tiktok_ads_souce/latest/)

The URL that redirects to the resource example repo is still empty [Zendesk Support](https://github.com/airbytehq/airbyte-dbt-models/issues/link)

**Comment by fvgm-spec** [comment]
Hi @marcosmarxm please let me know if this is a valid workaround for the first step assuming I am comparing the right code base from Fivetran side (as commented in the above comment) with [Tiktok Marketing Airbyte connector](https://docs.airbyte.com/integrations/sources/tiktok-marketing)

<html>
<body>
<h3 dir="auto" style="box-sizing: border-box; margin-top: var(--base-size-24); margin-bottom: var(--base-size-16); font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(197, 209, 222); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 39, 46); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Common Streams | Fivetran vs Airbyte Tiktok Ads Connectors</h3><markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block; color: rgb(197, 209, 222); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 39, 46); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Fivetran | Airbyte
-- | --
tiktok_ads__ad_group_report | AdGroups
tiktok_ads__campaign_report | Campaigns
tiktok_ads__advertiser_report | AdvertisersReportsHourly/Daily/Lifetime
tiktok_ads__ad_report | ❌ it doesn't exist
tiktok_ads__url_report | ❌ it doesn't exist

</markdown-accessiblity-table>
</body>
</html>

**Comment by marcosmarxm** [comment]
You must match tables used in https://github.com/fivetran/dbt_tiktok_ads_source/tree/main/models

**Comment by topefolorunso** [comment]
No update in over 5 days. Can I take this up? @marcosmarxm

**Comment by fvgm-spec** [comment]
yup @marcosmarxm please go ahead and reassign it, I didn't have enough time to work on it. Thanks!

**Comment by marcosmarxm** [comment]
All yours @topefolorunso

**Comment by topefolorunso** [comment]
Please confirm this @marcosmarxm 

Fivetran 									         | Airbyte
---------------------------------- | --
tiktok_ads__ad_group_history       | ad_groups
tiktok_ads__ad_group_report_hourly | ad_groups_reports_hourly
tiktok_ads__ad_history             | ads
tiktok_ads__ad_report_hourly       | ads_reports_hourly
tiktok_ads__advertiser             | advertisers
tiktok_ads__campaign_history       | campaigns
tiktok_ads__campaign_report_hourly | campaigns_reports_hourly

**Comment by marcosmarxm** [comment]
Let's move to the second phase @topefolorunso

**Comment by topefolorunso** [comment]
Confirm the following fields for `ad_group_history` @marcosmarxm 

Fivetran 									         | Airbyte
---------------------------------- | --
action_category_ids | action_categories
action_days | _same as fivetran_
adgroup_id | _same as fivetran_
adgroup_name | _same as fivetran_
advertiser_id | _same as fivetran_
age_groups | age
age_groups | _same as fivetran_
audience_type | _same as fivetran_
budget | _same as fivetran_
campaign_id | _same as fivetran_
category_id | category
campaign_name | display_name
frequency | _same as fivetran_
frequency_schedule | _same as fivetran_
gender | _same as fivetran_
interest_category_ids | interest_category_v_2
app_download_url | landing_page_url
languages | _same as fivetran_
modify_time | updated_at

**Comment by marcosmarxm** [comment]
Let's move forward with your suggestions @topefolorunso

**Comment by topefolorunso** [comment]
@marcosmarxm Can you please populate the tiktok marketing schema in the test postgres. Trying to test now and it's empty.
